name: Validate

on:
  push:
    branches: [ master ]

jobs:
  validate-windows:
    name: Validate (Windows)
    uses: iceshard-engine/.github/.github/workflows/rw_conan_create_package.yaml@main
    with:
      host: windows-latest
      conan_package: 'box2d/2.4.1@iceshard/stable'
      conan_config_url: 'https://github.com/iceshard-engine/conan-config.git'
      conan_options: '-s"build_type=Debug" -o"undefined_user_symbols=True" --build=openssl --build=box2d'

  validate-linux:
    name: Validate (Linux)
    uses: iceshard-engine/.github/.github/workflows/rw_conan_create_package.yaml@main
    with:
      host: ubuntu-latest
      conan_package: 'box2d/2.4.1@iceshard/stable'
      conan_config_url: 'https://github.com/iceshard-engine/conan-config.git'
      conan_options: '-s"build_type=Debug" -o"undefined_user_symbols=True" --build=openssl --build=box2d'
      conan_profile: 'gcc-11.0-linux-x86_64'
